default_tenant: MAIF

tenants:

  MAIF:
    machine_reference: MAIF-Solife
    environment: PROD

    repo: sahar-saidani/Solife-Standard
    branch: MAIF-Solife

    available_agents:
      - git
      - jenkins
      - installation
      - infrastructure
      - log