spring:
  application:
    name: chatops-vermeg
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
        default-requeue-rejected: false   # important : sans ça, épuisement des tentatives = requeue infini quand même

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:TwpkBLH1Lj5tApqcEm464UH7OItMTYH11aoQOPo4S70=}
    expiration: ${JWT_EXPIRATION:3600000}
  authentication:
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:2592000000}

chatops:
  authentication:
    frontend-base-url: ${AUTH_FRONTEND_BASE_URL:http://localhost:3000}
    mail-from: ${AUTH_MAIL_FROM:no-reply@chatops-vermeg.local}
  rabbitmq:
    exchange: chatops.agents.exchange
    dead-letter-exchange: chatops.agents.dlx
    queues:
      git: chatops.agent.git.queue
      jenkins: chatops.agent.jenkins.queue
      jira: chatops.agent.jira.queue
      log: chatops.agent.log.queue
      installation: chatops.agent.installation.queue
      infrastructure: chatops.agent.infrastructure.queue

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always