filebeat.inputs:

  - type: winlog
    id: windows-system
    name: System
    enabled: true
    tags: [windows, eventlog, system, logs-agent]
    fields_under_root: true
    fields:
      log_source: winlog

  - type: winlog
    id: windows-application
    name: Application
    enabled: true
    tags: [windows, eventlog, application, logs-agent]
    fields_under_root: true
    fields:
      log_source: winlog

  # À activer plus tard après avoir configuré les permissions.
  # - type: winlog
  #   id: windows-security
  #   name: Security
  #   enabled: true
  #   tags: [windows, eventlog, security, logs-agent]
  #   fields_under_root: true
  #   fields:
  #     log_source: winlog

  - type: winlog
    id: windows-setup
    name: Setup
    enabled: true
    tags: [windows, eventlog, setup, logs-agent]
    fields_under_root: true
    fields:
      log_source: winlog


processors:

  - add_host_metadata: ~

  - add_fields:
      target: ""
      fields:
        tenant_name: "MAIF"
        environment_name: "DEV"
        environment_type: "STANDALONE"
        machine_reference: "MAIF-WINDOWS-01"


output.logstash:
  hosts: ["127.0.0.1:5044"]
  loadbalance: false
  compression_level: 3
  ssl.enabled: false


logging.level: info
logging.to_files: true

logging.files:
  path: "C:/ProgramData/filebeat/logs"
  name: filebeat
  keepfiles: 7
  permissions: 0644